name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
        SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
        MAVEN_SIGNING_PRIVATE_KEY: ${{ secrets.MAVEN_SIGNING_PRIVATE_KEY }}
        MAVEN_SIGNING_PASSWORD: ${{ secrets.MAVEN_SIGNING_PASSWORD }}
      run: |
        echo $SONATYPE_NEXUS_USERNAME >> secrets.txt
        echo $SONATYPE_NEXUS_PASSWORD >> secrets.txt
        echo $MAVEN_SIGNING_PRIVATE_KEY >> secrets.txt
        echo $MAVEN_SIGNING_PASSWORD >> secrets.txt

    - name: Debugging with tmate
      uses: mxschmitt/action-tmate@v3.11
